#!/bin/bash

rm ./.DS_Store 2> /dev/null
rm */.DS_Store 2> /dev/null
rm */*/.DS_Store 2> /dev/null
rm */*/*/.DS_Store 2> /dev/null

version=$(cat config/compile_version_base)
suffix=$(cat config/compile_version_suffix)
suffix=$(($suffix+1))

echo "[$(date)] ++ Compilation de 'build/release-$version.$suffix.exe' ..." >> logs/compile

echo "build/release-$version.$suffix.exe" > config/last_version

g++ src/main.cpp src/classes/*/*.cpp -o build/release-$version.$suffix.exe 

if [ $? -eq 0 ]; then
	echo $suffix > config/compile_version_suffix
fi

git add logs/compile > /dev/null 2> /dev/null
git commit -m "[AUTO]Compilation de 'build/release-$version.$suffix.exe' ..." > /dev/null 2> /dev/null
git push > /dev/null 2> /dev/null
