#!/bin/bash
# TODO . config/config.var.sh

version=$(basename "$(cat config/last_version)")
log_fail_permission="740"
log_fail_path="logs/test_fails.logs"
log_runtest_path="logs/runtest.logs"
classes_dir="src/classes"
tests_dir="src/tests"

rm $log_fail_path 2> /dev/null
touch $log_fail_path
chmod $log_fail_permission $log_fail_path > /dev/null
echo "New log file created with permission $log_fail_permission : $log_fail_path"

for i in $classes_dir/*/*.test.cpp
do
	fileName=$(basename $i)
	testName="${fileName%%.*}"
	echo "Processing $testName..."
	ls $classes_dir/*-$testName.test > /dev/null 2> /dev/null
	if [ $? -eq -1 ]; then
		git add $i > /dev/null 2>&1
		git commit -m "Added new test : $testName" > /dev/null 2> /dev/null
		git push > /dev/null 2>&1
		echo "[$(date)] => Added new test $testName to $tests_dir" >> logs/general.logs
	fi
        rm $tests_dir/$version-$testName.test > /dev/null 2> /dev/null
		g++ $i -o "$tests_dir/$version-$testName.test" > /dev/null 2> /dev/null
        if [ $? -eq -1 ]; then
                echo "$testName : Compilation failed."
                echo "[$(date)] -- $testName : Compilation failed." >> $log_runtest_path
        	echo "g++ $i -o $tests_dir/$version-$testName.test" >> $log_fail_path
	else
		chmod +x $tests_dir/$version-$testName.test > /dev/null
		$tests_dir/$version-$testName.test
		err=$?
		if [ $err -eq -0 ]; then
			echo "$testName : Run test success."
			echo "[$(date)] ++ $testName : Run test success." >> $log_runtest_path
		else
			echo "$testName : Run test failed. (error code : $err)"
			echo "[$(date)] -- $testName : Run test failed. (error code : $err)" >> $log_runtest_path
		fi
	fi
done
